<?php
$collection  = $block->getTransactionCollection();
$count       = $collection->count();
$size        = $collection->getSize();
$limit       = $block->getLimit();
$currentPage = $block->getCurrentPage();
$start       = $size - (($currentPage - 1) * $limit);
?>

<?php if($count){ ?>
<div class="block lrw-block lrw-account-summary-listing">
	<div class="block-title">
		<strong><?php echo $block->getTitle()?$block->getTitle():''; ?></strong>
		<?php if ($size >= 8 && $block->getShowAlllink()): ?>
			<a class="action view" href="<?php /* @escapeNotVerified */ echo $block->getUrl('rewardpoints/transactions') ?>">
				<span><?php /* @escapeNotVerified */ echo __('View All') ?></span>
			</a>
		<?php endif; ?>
	</div>
	<div class="block-content">
		<div class="table-wrapper orders-recent">
			<table class="data-table table">
				<thead>
					<tr>
						<th><?php echo __('ID'); ?></th>
						<th><?php echo __('Title'); ?></th>
						<th><?php echo __('Points'); ?></th>
						<th><?php echo __('Created'); ?></th>
						<th><?php echo __('Expires'); ?></th>
						<th><?php echo __('Status'); ?></th>
					</tr>
				</thead>
				<tbody>
					<?php $i = 0; ?>
					<?php foreach ($collection as $_transaction) { ?>
					<?php $amount = $_transaction->getAmount(); ?>
					<tr class="<?php echo $i % 2 ? 'odd' : 'even' ?> <?php echo ($i == $count-1) ? 'last' : '' ?>">
						<td><?php echo ($start-$i) ?></td>
						<td><?php echo $_transaction->getTitle() ?></td>
						<td class="lrw-status-<?php echo str_replace(" ", "-", strtolower($_transaction->getStatusLabel())); ?>">
							<?php if($amount>0){ ?>
							<span>+<?php echo $amount; ?></span>
							<?php } else if($amount<0) { ?>
							<span><?php echo $amount; ?></span>
							<?php } else { ?>
							<span><?php echo $amount; ?></span>
							<?php } ?>
						</td>
						<td><?php echo $block->formatDate($_transaction->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></td>
						<td>
							<?php if($_transaction->getExpiresAt()) { ?>
							<?php echo $block->formatDate($_transaction->getExpiresAt(), \IntlDateFormatter::MEDIUM) ?>
							<?php } else { ?>
							<?php echo __('N\A'); ?>
							<?php } ?>
						</td>
						<td class="lrw-status-<?php echo str_replace(" ", "-", strtolower($_transaction->getStatusLabel())); ?>">
							<?php echo $_transaction->getStatusLabel() ?>
						</td>
					</tr>
					<?php $i++; ?>
					<?php } ?>
				</tbody>
			</table>
		</div>
		<?php echo $block->getChildHtml('toolbar'); ?>
	</div>
</div>
<?php } ?>