<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Tax\Block\Checkout\Grandtotal
 * @see \Magento\Tax\Block\Checkout\Grandtotal
 */
?>

<tr class="row-totals">
    <td style="<?php /* @escapeNotVerified */ echo $block->getStyle() ?>" class="admin__total-mark" colspan="<?php /* @escapeNotVerified */ echo $block->getColspan(); ?>">
        <?php /* @escapeNotVerified */ echo $block->getTotal()->getTitle(); ?>
    </td>
    <td style="<?php /* @escapeNotVerified */ echo $block->getStyle() ?>" class="admin__total-amount">
        <?php /* @escapeNotVerified */ echo $block->getTotal()->getValue() ?>
    </td>
</tr>
