<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Catalog\Block\Adminhtml\Form\Renderer\Fieldset\Element
 */
?>
<?php
/* @var $block \Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element */
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note admin__field-note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox' || $element->getExtType() == 'radio';
$addOn = $element->getBeforeElementHtml() || $element->getAfterElementHtml();
$fieldId = ($element->getHtmlId()) ? ' id="attribute-' . $element->getHtmlId() . '-container"' : '';
$entity = $element->getEntityAttribute();
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= ($entity && $entity->getIsUserDefined()) ? ' user-defined type-' . $entity->getFrontendInput() : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
. $block->getUiId('form-field', $element->getId());
?>

<?php //$block->checkFieldDisable() ?>
<?php
$elementToggleCode = $element->getToggleCode() ? $element->getToggleCode()
: 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';
?>
<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?php echo $element->getElementHtml() ?>
    <?php else: ?>
        <div<?php /* @escapeNotVerified */ echo $fieldAttributes ?> data-attribute-code="<?php echo $element->getHtmlId() ?>"
        data-apply-to="<?php echo $block->escapeHtml($this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode(
        $element->hasEntityAttribute() ? $element->getEntityAttribute()->getApplyTo() : []
        ))?>"
        >

        <?php
        $classes = 'lrw-no-guide';
        if($guide = $element->getGuide()){
            $classes = ' lrw-guide';
        }
        ?>

        <?php if ($elementBeforeLabel): ?>
            <?php echo $block->getElementHtml() ?>
            <?php echo $element->getLabelHtml('', $block->getScopeLabel()) ?>
            <?php /* @escapeNotVerified */ echo $note ?>
        <?php else: ?>
            <?php echo $element->getLabelHtml('', $block->getScopeLabel()) ?>
            <div class="admin__field-control control <?php echo $classes ?>">
                <div class="field-inner">
                    <?php if($guide = $element->getGuide()){ ?>
                    <div class="admin__field-tooltip">
                        <a class="admin__field-tooltip-action action-help" target="_blank" tabindex="1" href="javascript:void(0);"></a>
                        <div class="admin__field-tooltip-content">
                            <?php echo $guide; ?>
                        </div>
                    </div>
                    <?php } ?>
                    <?php /* @escapeNotVerified */ echo($addOn) ? '<div class="addon">' . $block->getElementHtml() . '</div>' : $block->getElementHtml(); ?>

                </div>
                <?php /* @escapeNotVerified */ echo $note ?>
            </div>
        <?php endif; ?>


        


        <?php if(!$this->getData('is_scope_global')){ ?>
            <div class="field-service">
                <?php if ($block->canDisplayUseDefault()): ?>
                <label for="<?php echo $element->getHtmlId() ?>_default" class="choice use-default">
                    <input <?php if ($element->getReadonly()):?> disabled="disabled"<?php endif; ?>
                    type="checkbox"
                    name="use_default[]"
                    class="use-default-control"
                    id="<?php echo $element->getHtmlId() ?>_default"
                    <?php if ($element->getDisabled()): ?> checked="checked"<?php endif; ?>
                    onclick="<?php /* @escapeNotVerified */ echo $elementToggleCode; ?>"
                    value="<?php /* @escapeNotVerified */ echo $block->getElement()->getName() ?>"/>
                    <span class="use-default-label"><?php /* @escapeNotVerified */ echo __('Use Default Value') ?></span>
                </label>
            <?php endif; ?>
        </div>
        <?php } ?>
    </div>
<?php endif; ?>
<?php endif; ?>

