<?php
$rewardsData = $this->helper('Lof\RewardPoints\Helper\Data');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$point       = $block->getPoint();
$spendPoint  = $block->getSpendPoint();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$path = 'lof/rewardpoints/default/btn_remove.gif';
$button_url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . $path;
?>
<?php if($point || $spendPoint) { ?>
<div class="lrw-product-points">
	<?php if ($point) { ?>
	<?php echo __('Earn %1 for purchasing this product', $rewardsData->formatPoints($point)); ?>
	<?php } ?>
	<?php if ($spendPoint) { ?>
	<?php echo __('Buy with %1', $rewardsData->formatPoints($spendPoint)); ?>
	<?php } ?>
</div>
<?php } ?>
<?php $pointsSpent = $block->getPointsSpending() ?>
<?php if($pointsSpent) { ?>
<div class="lrw-points-spent">
	<div class="label">
		<?php echo __('Points Spent:'); ?>
	</div>
	<div class="lrw-points-spent-message">
		<ul>
			<?php foreach ($pointsSpent as $ruleId => $item) { ?>
			<li>
				<span class="lrw-points-spent-item">
					<span class="lrw-spent-points"><?php echo $rewardsData->formatPoints(($item['points']) * $item['steps']); ?></span>,
					<span class="lrw-spent-discount"><?php echo __('%1 off', $priceHelper->currency(($item['discount'] * $item['steps']), true, false)); ?></span>
				</span>
				<a href="<?php echo $block->getCancelPointsUrl($ruleId); ?>" class="lrw-points-spent-btn">
					<img src="<?php echo $button_url; ?>" title="<?php __('Remove Rule'); ?>">
				</a>
			</li>
			<?php } ?>
		</ul>
	</div>
</div>
<?php } ?>